### ISSUE TITLE
OOM kill agent

### ISSUE THREAD

**Issue by kkopanidis** [coroot/coroot-node-agent#11]
Hello coroot team, I have another issue, now centered on the node-agent.
Attached metrics from lens:
[](url)
![c55edbfc-618d-4f6d-8737-7309f7fc1104](https://user-images.githubusercontent.com/9095396/223371874-1206b338-d845-4032-8260-2196ebaf5222.jpg)
![5fc153cf-d4b2-47fa-a1b8-8b7e6779987e](https://user-images.githubusercontent.com/9095396/223371887-c68fcae6-b434-4e90-be6c-58f43876d5e4.jpg)
![36d2fa8d-6077-4de1-995a-250a5c598204](https://user-images.githubusercontent.com/9095396/223371892-61860eaf-841a-40f5-a939-55eac58a4b70.jpg)

We are reaching the 1GB default memory limit on 3 nodes. We have coroot running in 3-4 different clusters and this behaviour appears only in one. We have tried looking into node differences but we didn't find anything. Do you have any idea why these spikes might be happening and how it could be mitigated?

**Comment by def** [comment]
@kkopanidis thank you for the report!
Can you please share the CPU and Memory profiles of an affected agent?
```
curl -o mem_profile.tgz 'http://<agent_ip>:<agent_port>/debug/pprof/heap'
curl -o cpu_profile.tgz 'http://<agent_ip>:<agent_port>/debug/pprof/profile?seconds=60'
```

**Comment by kkopanidis** [comment]
[cpu_profile.tgz](https://github.com/coroot/coroot-node-agent/files/10909019/cpu_profile.tgz)
[mem_profile.tgz](https://github.com/coroot/coroot-node-agent/files/10909021/mem_profile.tgz)
There you go!

**Comment by def** [comment]
No, something went wrong. These files contain only `404 page not found`.

**Comment by kkopanidis** [comment]
[cpu_profile.tgz](https://github.com/coroot/coroot-node-agent/files/10910806/cpu_profile.tgz)
[mem_profile.tgz](https://github.com/coroot/coroot-node-agent/files/10910808/mem_profile.tgz)
Yes my bad, these seem correct

**Comment by def** [comment]
@kkopanidis could you please update coroot-node-agent to version 1.7.1 and check its memory and CPU consumption?

**Comment by kkopanidis** [comment]
Works much better, CPU on ~10% and memory at ~700mb (for the pod that had issues before). Will continue monitoring and let you know, if it starts misbehaving again. Thanks for the assistance
