### ISSUE TITLE
On EKS 1.22 missing some node_cloud_info needed for cost analysis

### ISSUE THREAD

**Issue by YoranSys** [coroot/coroot-node-agent#13]
Hello, 
using latest node agent helm chart I can't get cost analysis, after some research on prometheus it's seem some label are missing based on your [documentation](https://coroot.com/docs/metric-exporters/node-agent/metrics#node_cloud_info)  

Here some label missing on `node_cloud_info`  : 
- provider
- instance_type
- instance_life_cycle
- region
- availability_zone_id

My current label: 
```
{
    account_id="xxxxx",
    availability_zone_id="xxxxxx",
    instance="xxxxxxxx:80",
    instance_id="i-00fxxxxxxxxxxx",
    local_ipv4="10.xxxxxxxx",
    machine_id="ec2708xxxxxxxxxxxxxxxx",
}
```

Some complementary information: 
![image](https://user-images.githubusercontent.com/11197007/230289524-ad7976bd-cd62-4e80-b656-f0d88f82e9fe.png)

**Comment by def** [comment]
@YoranSys thank you for the report. 
It's fixed in v1.7.6
