### ISSUE TITLE
bug runing in kernel 6.0.x 

### ISSUE THREAD

**Issue by gefire** [coroot/coroot-node-agent#152]
func SetKernelVersion(version string) error {
	v, err := VersionFromString(version)
	if err != nil || v.Minor == 0 {
		return fmt.Errorf("invalid kernel version: %s", version)
	}
	kernelVersion = v
	return nil
}

this code run in 6.0.x will return invalid kernel version

**Comment by apetruhin** [comment]
@gefire, thanks for the report

https://github.com/coroot/coroot-node-agent/releases/tag/v1.22.6
