### ISSUE TITLE
[Feature Request] Supports mongo4 protocol recognizing.

### ISSUE THREAD

**Issue by StLeoX** [coroot/coroot-node-agent#165]
# Problem
![image](https://github.com/user-attachments/assets/339f0067-88c4-4a0b-9212-4a813a8fbab0)
The request sent to the MongoDB database may not be collected because of the protocol version problem.

Here I use the payload [`sok-shop`](https://github.com/microservices-demo/microservices-demo), which uses `mongo:4.4.5` image and the MongoDB 4 protocol.

[Starting in MongoDB 5.1](https://www.mongodb.com/docs/manual/legacy-opcodes/), OP_MSG and OP_COMPRESSED are the only supported opcodes to send requests to a MongoDB server.

# Solution
According to current MongoDB parser implement in eBPF programs, we only filter OP_MSG and OP_COMPRESSED. Maybe we can also filter OP_UPDATE and other legacy keywords?

**Comment by def** [comment]
According to MongoDB's support policy (https://www.mongodb.com/legal/support-policy/lifecycles), MongoDB 4.4 reached its End of Life (EOL) in February 2024

**Comment by StLeoX** [comment]
So if I implement this, test it and summit a PR, would your project approve it? @def

**Comment by def** [comment]
I don't think so, since this code will need future support

**Comment by StLeoX** [comment]
Fine.
