### ISSUE TITLE
Too many errors at lunch of node

### ISSUE THREAD

**Issue by gkalwig** [coroot/coroot-node-agent#17]
Hi,

We have been experiencing a situation where, upon starting the k8s node, the node-agent begins producing tens of thousands of error logs for several seconds. This sudden surge in log generation is causing disruptions in our logging system's functionality.

I have look for the available configuration options, including loglvl management for the node agent, but I have not found any configuration. It seems that there is no existing configuration option to mitigate the excessive logging behavior of the node agent and no way to change loglvl of node-agent.

This issue has been negatively impacting our system's performance and hampering our ability to effectively monitor and analyze logs. We would greatly appreciate any assistance or guidance you can provide to help us resolve this problem.

![image](https://github.com/coroot/coroot-node-agent/assets/87004230/8257b89f-4108-4141-bde3-736b65676636)

**Comment by def** [comment]
@gkalwig thank you for the report. 
We will add a rate limiter for logging to prevent situations like that.

**Comment by def** [comment]
@gkalwig, both problems (too aggressive logging and support for containers within the `runtime.slice` cgroup) have been fixed in v1.8.3

**Comment by gkalwig** [comment]
@def thanks! I'll test it and get back to you next week if it's resolved.
