### ISSUE TITLE
crashloop on panic with labels

### ISSUE THREAD

**Issue by gkalwig** [coroot/coroot-node-agent#25]
Hello, from today we occured error: 
![image](https://github.com/coroot/coroot-node-agent/assets/87004230/79473186-bc88-4968-bdff-9fa7b3cea27e)

agent version: 1.8.8
kernel version: 5.10.184-175.731.amzn2.x86_64
EKS 1.26

I can send you contains of blurred area if you needed, but I need to know there are no sensitive data about our system.

**Comment by apetruhin** [comment]
Hey @gkalwig, thank you for the report. Please, update `coroot-node-agent` to the latest version (1.8.9).

**Comment by gkalwig** [comment]
Thanks, we had 2d19h uptime, so it looks good :)
