### ISSUE TITLE
Error running coroot-node-agent on docker and WSL2

### ISSUE THREAD

**Issue by ajacobsedt** [coroot/coroot-node-agent#3]
Hi, 
Thanks for such a great tool. 
I'm just running coroot-node-agent on Docker using the command provided in the readme file and I'm getting the following error: 
`
I0926 05:12:35.317767   95622 main.go:76] agent version: 1.0.21

I0926 05:12:35.317978   95622 main.go:82] hostname: docker-desktop

I0926 05:12:35.317983   95622 main.go:83] kernel version: 5.10.102.1-microsoft-standard-WSL2

W0926 05:12:35.318069   95622 main.go:65] failed to read machine-id: open /proc/1/root/sys/devices/virtual/dmi/id/product_uuid: no such file or directory

W0926 05:12:35.319393   95622 main.go:65] failed to read machine-id: open /proc/1/root/etc/machine-id: no such file or directory

W0926 05:12:35.319610   95622 main.go:65] failed to read machine-id: open /proc/1/root/var/lib/dbus/machine-id: no such file or directory

I0926 05:12:35.319757   95622 metadata.go:63] cloud provider: 

I0926 05:12:35.319781   95622 collector.go:152] instance metadata: <nil>

F0926 05:12:35.320025   95622 main.go:103] netlink receive: no such file or directory`

Not sure If I have missed something, I'm running windows 11 and WSL2. 

Thanks for your help. 
Best Regards, 
Alex

**Comment by apetruhin** [comment]
Hi @ajacobsedt, unfortunately node-agent does not support WSL.

**Comment by Corey-J** [comment]
Interesting, I was planning on using this, although my primary use would be via the WSL.

Are there any plans for WSL support?

**Comment by ajacobsedt** [comment]
Thanks for the update @apetruhin. 
Considering coroot won't work without the agent, is there any way we can use it on our local cluster which we run using kind?
Thanks.

**Comment by def** [comment]
Unfortunately, we currently have no plans to support WSL.
