### ISSUE TITLE
Bug in documentation 

### ISSUE THREAD

**Issue by KKulishov** [coroot/coroot-node-agent#30]
Hello!

you have an error in the documentation. [node-agent](https://coroot.com/docs/metric-exporters/node-agent/installation)

set flags
`--no-parse-logs        Disable container logs parsing`

but  if set this flag ,  node-agent error:

`coroot-node-agent: error: unknown long flag '--no-parse-logs', try --help`
 
but in your code it says [flag node-agent](https://github.com/coroot/coroot-node-agent/blob/main/flags/flags.go)

`DisableLogParsing = kingpin.Flag("disable-log-parsing", "Disable container log parsing").Default("false").Bool()`

please correct the documentation  [node-agent flags](https://coroot.com/docs/metric-exporters/node-agent/installation)

you have a great project!

**Comment by def** [comment]
Fixed! Thanks for telling us.
