### ISSUE TITLE
Error in Docker Desktop WSL2 while install coroot-node-agent

### ISSUE THREAD

**Issue by rmn-lux** [coroot/coroot-node-agent#33]
Hello! I installed coroot via helm chart: `helm install --namespace coroot --create-namespace coroot coroot/coroot`

My env: Docker Desktop v4.22 in Windows 11, WSL2

After run all pods coroot-node-agent don`t start, errors in log:

 Unable to get object /proc/1/root/sys/fs/bpf/tc/globals/cilium_ct4_global: no such file or directory Unable to get object /proc/1/root/sys/fs/bpf/tc/globals/cilium_ct6_global: no such file or directory Unable to get object /proc/1/root/sys/fs/bpf/tc/globals/cilium_lb4_backends_v2: no such file or directory Unable to get object /proc/1/root/sys/fs/bpf/tc/globals/cilium_lb4_backends_v3: no such file or directory Unable to get object /proc/1/root/sys/fs/bpf/tc/globals/cilium_lb6_backends_v2: no such file or directory Unable to get object /proc/1/root/sys/fs/bpf/tc/globals/cilium_lb6_backends_v3: no such file or directory

<img width="869" alt="Screenshot_1" src="https://github.com/coroot/coroot-node-agent/assets/6730162/1ba3a99e-3821-444a-998b-bb98d8c871c4">

Please tell what the problem? Probably, on WSL2 it could not start by design (ebpf and so on)?

**Comment by def** [comment]
Unfortunately, Coroot cannot run on WSL due to limitations involving eBPF, netlink, and other factors
