### ISSUE TITLE
go mod unknown revision

### ISSUE THREAD

**Issue by blue-troy** [coroot/coroot-node-agent#37]
current go mod file:
https://github.com/coroot/coroot-node-agent/blob/172da08b770c4c5416a36e2817291f4ca0b4a9c7/go.mod#L142
but this revision of taskstats do not exist and the error occur:

```log
go: github.com/mdlayher/taskstats@v0.0.0-00010101000000-000000000000 (replaced by github.com/coroot/taskstats@v0.0.0-20230306100019-4faaee49e6cf): version "v0.0.0-20230306100019-4faaee49e6cf" invalid: unknown revision 4faaee49e6cf
```

**Comment by blue-troy** [comment]
20230306100019-4faaee49e6cf do not exit, maybe 20230306104127-411100e19e3a is the right revision?

**Comment by apetruhin** [comment]
It exists somewhere https://github.com/coroot/taskstats/commit/4faaee49e6cf9ee9ab04aa02bc1516a8b9e6bf03 😄 

We can switch back to https://github.com/mdlayher/taskstats. Could you please remove the replacement and update github.com/mdlayher/taskstats to the latest version?

**Comment by blue-troy** [comment]
This issue may be caused by my Golang configuration or something else. I will close this issue and create a new one about switch back to https://github.com/mdlayher/taskstats.
