### ISSUE TITLE
Error Logging Flags 

### ISSUE THREAD

**Issue by sumeet-zuora** [coroot/coroot-node-agent#4]
How to set agent to log only errors, seems the default spits lot of logs

**Comment by Schaudhari7565** [comment]
@apetruhin do you know, how we can reduce the logging seems to be lot of logs

**Comment by apetruhin** [comment]
Usually, the agent doesn't log much. So, maybe in your case, something goes wrong. Can you please send us a sample from your logs to support@coroot.com?

**Comment by sumeet-zuora** [comment]
Seent an email with sample logs

**Comment by apetruhin** [comment]
The latest version (1.1.1) logs much less. Please upgrade.
