### ISSUE TITLE
Do we have a plan to track DNS?

### ISSUE THREAD

**Issue by guolifu** [coroot/coroot-node-agent#60]
DNS resolution tracking is often crucial and easily overlooked in Kubernetes.

**Comment by def** [comment]
Certainly, we have plans to integrate this capability into both the agent and Coroot.

**Comment by guolifu** [comment]
> 当然，我们计划将此功能集成到代理和 Coroot 中。

Great, we hope to see it soon😉

**Comment by guolifu** [comment]
> Certainly, we have plans to integrate this capability into both the agent and Coroot.

Great, we hope to see it soon😉

**Comment by guolifu** [comment]
> Certainly, we have plans to integrate this capability into both the agent and Coroot.

Could you provide an example, such as which hook point to use. I take this opportunity to learn.

**Comment by def** [comment]
It's hard to determine the right hook without doing research...

**Comment by def** [comment]
We've implemented DNS monitoring: https://coroot.com/blog/why-should-you-care-about-dns-observability
