### ISSUE TITLE
How to disable profiling

### ISSUE THREAD

**Issue by KKulishov** [coroot/coroot-node-agent#61]
Hello!

I see in the code

`
profiling.Start()
defer profiling.Stop()
`
Is it possible to add a condition that specifies whether to enable or not profiling?

**Comment by apetruhin** [comment]
@KKulishov,
It won't start if no PROFILES_ENDPOINT environment variable is configured.
https://github.com/coroot/coroot-node-agent/blob/4a80e36036cc21044461809c9c62a240defeb603/profiling/profiling.go#L50

**Comment by KKulishov** [comment]
Thank you
