### ISSUE TITLE
RSS memory calculation overflow for some low in resource usage processes

### ISSUE THREAD

**Issue by btmc** [coroot/coroot-node-agent#84]
For some nodes in my setup in node view, **Memory consumers, bytes** graph I see some processes have `18.45E` memory consumption, so the graph gets unusable.

My nodes in question run on Debian 11, using cgroups v2.

It seems to be a consequence of current RSS calculation in the agent [here](https://github.com/coroot/coroot-node-agent/blob/v1.19.1/cgroup/memory.go#L60), wherein RSS is calculated as: `current - vars["file"],`.

For example, for `system-getty.slice` cgroup I see:

```
cat /sys/fs/cgroup/system.slice/system-getty.slice/memory.current
249856
cat /sys/fs/cgroup/system.slice/system-getty.slice/memory.stat | grep ^file\
file 270336
```

So subtraction gives negative result.

**Comment by def** [comment]
@btmc thank you for the report. We'll take a look ASAP
