### ISSUE TITLE
Agent does not run inside a KinD cluster

### ISSUE THREAD

**Issue by steveww** [coroot/coroot-node-agent#9]
Running a KinD cluster on Linux for testing. The coroot agent fails to start with this message

netlink receive: no such file or directory

Is there any work around? It would be great to be able to test on KinD rather than spin up a real cluster on GKE.

**Comment by def** [comment]
Unfortunately, the agent cannot run in docker-in-docker environments yet.
[Here](https://github.com/coroot/coroot/issues/10#issuecomment-1345201225) is an explanation of the problem.

**Comment by steveww** [comment]
OK thanks for the details.
Might be an idea to add this little gem of information to the `README`
